name: Deploy Docs (MkDocs)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and theme
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build and deploy to GitHub Pages (gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force

